project:
  type: website

website:
  title: "Soul Guard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - soulguard.qmd
      - recommendation.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



