project:
  type: website

website:
  title: "Soul Guard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: soulguard.qmd
        text: SoulGuard
      - href: recommendation.qmd
        text: OurRecommendations
    right:
      - href: about.qmd
        text: About  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



